### ISSUE TITLE
How Can We Calculate and Include Confidence Scores during inference?

### ISSUE THREAD

**Issue by Shohruh72** [yihuacheng/IVGaze#2]
Could you provide guidance or implement a feature to calculate and include confidence scores in the inference output? This would help users better assess the accuracy and reliability of the gaze predictions.

**Comment by CrossEntropy** [comment]
> Could you provide guidance or implement a feature to calculate and include confidence scores in the inference output? This would help users better assess the accuracy and reliability of the gaze predictions.

Hi, @Shohruh72. In PTR model, there is only one output i.e. Pitch, Yaw and there is no option of confidence.

**Comment by Shohruh72** [comment]
Thank you
